name = "badminton-score"
main = "src/index.ts"
compatibility_date = "2025-09-27"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "badminton"
database_id = "c4860c60-03c2-4421-90dc-d95bbede40fa"
